### ISSUE TITLE
syn - crates.io: Rust Package Registry

### ISSUE THREAD

**Issue by tg-z** [tg-z/web-clip#888]
Cargo.toml

`syn = "1.0.14"`

[![](https://api.travis-ci.org/dtolnay/syn.svg?branch=master)
](https://travis-ci.org/dtolnay/syn) [![](https://img.shields.io/crates/v/syn.svg)
](https://crates.io/crates/syn) [![](https://img.shields.io/badge/api-rustdoc-blue.svg)
](https://docs.rs/syn/1.0/syn/) [![](https://img.shields.io/badge/rustc-1.31+-lightgray.svg)
](https://blog.rust-lang.org/2018/12/06/Rust-1.31-and-rust-2018.html)

Syn is a parsing library for parsing a stream of Rust tokens into a syntax tree of Rust source code.

Currently this library is geared toward use in Rust procedural macros, but contains some APIs that may be useful more generally.

*   **Data structures** — Syn provides a complete syntax tree that can represent any valid Rust source code. The syntax tree is rooted at [`syn::File`](https://docs.rs/syn/1.0/syn/struct.File.html) which represents a full source file, but there are other entry points that may be useful to procedural macros including [`syn::Item`](https://docs.rs/syn/1.0/syn/enum.Item.html), [`syn::Expr`](https://docs.rs/syn/1.0/syn/enum.Expr.html) and [`syn::Type`](https://docs.rs/syn/1.0/syn/enum.Type.html).
    
*   **Derives** — Of particular interest to derive macros is [`syn::DeriveInput`](https://docs.rs/syn/1.0/syn/struct.DeriveInput.html) which is any of the three legal input items to a derive macro. An example below shows using this type in a library that can derive implementations of a user-defined trait.
    
*   **Parsing** — Parsing in Syn is built around [parser functions](https://docs.rs/syn/1.0/syn/parse/index.html) with the signature `fn(ParseStream) -> Result<T>`. Every syntax tree node defined by Syn is individually parsable and may be used as a building block for custom syntaxes, or you may dream up your own brand new syntax without involving any of our syntax tree types.
    
*   **Location information** — Every token parsed by Syn is associated with a `Span` that tracks line and column information back to the source of that token. These spans allow a procedural macro to display detailed error messages pointing to all the right places in the user's code. There is an example of this below.
    
*   **Feature flags** — Functionality is aggressively feature gated so your procedural macros enable only what they need, and do not pay in compile time for all the rest.
    

If you get stuck with anything involving procedural macros in Rust I am happy to provide help even if the issue is not related to Syn. Please file a ticket in this repo.

_Version requirement: Syn supports rustc 1.31 and up._

[_Release notes_](https://github.com/dtolnay/syn/releases)

  

[](#resources)Resources
-----------------------

The best way to learn about procedural macros is by writing some. Consider working through [this procedural macro workshop](https://github.com/dtolnay/proc-macro-workshop) to get familiar with the different types of procedural macros. The workshop contains relevant links into the Syn documentation as you work through each project.

  

[](#example-of-a-derive-macro)Example of a derive macro
-------------------------------------------------------

The canonical derive macro using Syn looks like this. We write an ordinary Rust function tagged with a `proc_macro_derive` attribute and the name of the trait we are deriving. Any time that derive appears in the user's code, the Rust compiler passes their data structure as tokens into our macro. We get to execute arbitrary Rust code to figure out what to do with those tokens, then hand some tokens back to the compiler to compile into the user's crate.

```
[dependencies]
syn = "1.0"
quote = "1.0"

[lib]
proc-macro = true

```

```
extern crate proc_macro;

use proc_macro::TokenStream;
use quote::quote;
use syn::{parse_macro_input, DeriveInput};

#[proc_macro_derive(MyMacro)]
pub fn my_macro(input: TokenStream) -> TokenStream {
    
    let input = parse_macro_input!(input as DeriveInput);

    
    let expanded = quote! {
        
    };

    
    TokenStream::from(expanded)
}

```

The [`heapsize`](https://github.com/dtolnay/syn/blob/master/examples/heapsize) example directory shows a complete working implementation of a derive macro. It works on any Rust compiler 1.31+. The example derives a `HeapSize` trait which computes an estimate of the amount of heap memory owned by a value.

```
pub trait HeapSize {
    
    fn heap_size_of_children(&self) -> usize;
}

```

The derive macro allows users to write `#[derive(HeapSize)]` on data structures in their program.

```
#[derive(HeapSize)]
struct Demo<'a, T: ?Sized> {
    a: Box<T>,
    b: u8,
    c: &'a str,
    d: String,
}

```

  

[](#spans-and-error-reporting)Spans and error reporting
-------------------------------------------------------

The token-based procedural macro API provides great control over where the compiler's error messages are displayed in user code. Consider the error the user sees if one of their field types does not implement `HeapSize`.

```
#[derive(HeapSize)]
struct Broken {
    ok: String,
    bad: std::thread::Thread,
}

```

By tracking span information all the way through the expansion of a procedural macro as shown in the `heapsize` example, token-based macros in Syn are able to trigger errors that directly pinpoint the source of the problem.

```
error[E0277]: the trait bound `std::thread::Thread: HeapSize` is not satisfied
 --> src/main.rs:7:5
  |
7 |     bad: std::thread::Thread,
  |     ^^^^^^^^^^^^^^^^^^^^^^^^ the trait `HeapSize` is not implemented for `std::thread::Thread`

```

  

[](#parsing-a-custom-syntax)Parsing a custom syntax
---------------------------------------------------

The [`lazy-static`](https://github.com/dtolnay/syn/blob/master/examples/lazy-static) example directory shows the implementation of a `functionlike!(...)` procedural macro in which the input tokens are parsed using Syn's parsing API.

The example reimplements the popular `lazy_static` crate from [crates.io](http://crates.io/ "Linkify Plus Plus") as a procedural macro.

```
lazy_static! {
    static ref USERNAME: Regex = Regex::new("^[a-z0-9_-]{3,16}$").unwrap();
}

```

The implementation shows how to trigger custom warnings and error messages on the macro input.

```
warning: come on, pick a more creative name
  --> src/main.rs:10:16
   |
10 |     static ref FOO: String = "lazy_static".to_owned();
   |                ^^^

```

  

[](#testing)Testing
-------------------

When testing macros, we often care not just that the macro can be used successfully but also that when the macro is provided with invalid input it produces maximally helpful error messages. Consider using the [`trybuild`](https://github.com/dtolnay/trybuild) crate to write tests for errors that are emitted by your macro or errors detected by the Rust compiler in the expanded code following misuse of the macro. Such tests help avoid regressions from later refactors that mistakenly make an error no longer trigger or be less helpful than it used to be.

  

[](#debugging)Debugging
-----------------------

When developing a procedural macro it can be helpful to look at what the generated code looks like. Use `cargo rustc -- -Zunstable-options --pretty=expanded` or the [`cargo expand`](https://github.com/dtolnay/cargo-expand) subcommand.

To show the expanded code for some crate that uses your procedural macro, run `cargo expand` from that crate. To show the expanded code for one of your own test cases, run `cargo expand --test the_test_case` where the last argument is the name of the test file without the `.rs` extension.

This write-up by Brandon W Maister discusses debugging in more detail: [Debugging Rust's new Custom Derive system](https://quodlibetor.github.io/posts/debugging-rusts-new-custom-derive-system/).

  

[](#optional-features)Optional features
---------------------------------------

Syn puts a lot of functionality behind optional features in order to optimize compile time for the most common use cases. The following features are available.

*   **`derive`** _(enabled by default)_ — Data structures for representing the possible input to a derive macro, including structs and enums and types.
*   **`full`** — Data structures for representing the syntax tree of all valid Rust source code, including items and expressions.
*   **`parsing`** _(enabled by default)_ — Ability to parse input tokens into a syntax tree node of a chosen type.
*   **`printing`** _(enabled by default)_ — Ability to print a syntax tree node as tokens of Rust source code.
*   **`visit`** — Trait for traversing a syntax tree.
*   **`visit-mut`** — Trait for traversing and mutating in place a syntax tree.
*   **`fold`** — Trait for transforming an owned syntax tree.
*   **`clone-impls`** _(enabled by default)_ — Clone impls for all syntax tree types.
*   **`extra-traits`** — Debug, Eq, PartialEq, Hash impls for all syntax tree types.
*   **`proc-macro`** _(enabled by default)_ — Runtime dependency on the dynamic library libproc_macro from rustc toolchain.

  

[](#proc-macro-shim)Proc macro shim
-----------------------------------

Syn operates on the token representation provided by the [proc-macro2](https://docs.rs/proc-macro2/1.0.0/proc_macro2/) crate from [crates.io](http://crates.io/ "Linkify Plus Plus") rather than using the compiler's built in proc-macro crate directly. This enables code using Syn to execute outside of the context of a procedural macro, such as in unit tests or [build.rs](http://build.rs/ "Linkify Plus Plus"), and we avoid needing incompatible ecosystems for proc macros vs non-macro use cases.

In general all of your code should be written against proc-macro2 rather than proc-macro. The one exception is in the signatures of procedural macro entry points, which are required by the language to use `proc_macro::TokenStream`.

The proc-macro2 crate will automatically detect and use the compiler's data structures when a procedural macro is active.

  

#### [](#license)License

Licensed under either of [Apache License, Version 2.0](https://github.com/dtolnay/syn/blob/master/LICENSE-APACHE) or [MIT license](https://github.com/dtolnay/syn/blob/master/LICENSE-MIT) at your option.  
Unless you explicitly state otherwise, any contribution intentionally submitted for inclusion in this crate by you, as defined in the Apache-2.0 license, shall be dual licensed as above, without any additional terms or conditions.

Last Updated

23 days ago

 [![](https://travis-ci.org/dtolnay/syn.svg?branch=master)](https://travis-ci.org/dtolnay/syn) 

### License

MIT OR Apache-2.0

### Owners

*    [![](https://avatars2.githubusercontent.com/u/1940490?v=4&s=64)](https://crates.io/users/dtolnay) 

### Stats Overview

21,628,178 Downloads all time

138 Versions published

#### Downloads over the last 90 days

Other1.0.101.0.111.0.121.0.131.0.14Dec 2019Jan 2020Feb 2020025,00050,00075,000100,000

| Date | 1.0.14 | 1.0.14 7-day avg. | 1.0.13 | 1.0.13 7-day avg. | 1.0.12 | 1.0.12 7-day avg. | 1.0.11 | 1.0.11 7-day avg. | 1.0.10 | 1.0.10 7-day avg. | Other | Other 7-day avg. |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Feb 11, 2020 | 18,183 | 18,081.3 | 2,656 | 2,584.7 | 60 | 70.0 | 3,773 | 3,281.0 | 35 | 31.7 | 38,234 | 33,628.0 |
| Feb 10, 2020 | 19,048 | 18,616.1 | 2,956 | 2,582.4 | 67 | 75.9 | 3,891 | 3,349.1 | 31 | 33.9 | 40,723 | 33,469.3 |
| Feb 9, 2020 | 10,626 | 19,035.0 | 1,513 | 2,503.1 | 50 | 75.3 | 1,712 | 3,382.6 | 54 | 30.0 | 15,683 | 33,331.7 |
| Feb 8, 2020 | 11,286 | 19,459.9 | 1,150 | 2,532.1 | 19 | 104.3 | 1,799 | 3,418.0 | 26 | 34.7 | 15,194 | 33,772.9 |
| Feb 7, 2020 | 18,624 | 20,021.4 | 2,850 | 2,446.3 | 72 | 119.4 | 3,895 | 3,431.1 | 17 | 43.3 | 39,377 | 34,329.1 |
| Feb 6, 2020 | 21,197 | 20,462.6 | 2,931 | 2,427.0 | 78 | 144.6 | 3,856 | 3,564.3 | 38 | 52.3 | 39,489 | 36,002.3 |
| Feb 5, 2020 | 22,404 | 20,979.3 | 3,468 | 2,323.6 | 87 | 166.4 | 3,820 | 3,723.4 | 34 | 78.0 | 42,662 | 37,105.4 |
| Feb 4, 2020 | 23,384 | 21,256.6 | 3,225 | 2,337.9 | 117 | 175.9 | 3,994 | 3,888.9 | 22 | 96.9 | 42,268 | 38,233.6 |
| Feb 3, 2020 | 22,792 | 21,238.4 | 2,940 | 2,336.9 | 108 | 189.4 | 4,368 | 3,891.9 | 46 | 108.0 | 39,612 | 38,747.3 |
| Feb 2, 2020 | 13,558 | 21,260.9 | 958 | 2,438.7 | 46 | 194.3 | 1,946 | 3,926.6 | 27 | 120.3 | 14,720 | 39,459.4 |
| Feb 1, 2020 | 14,260 | 21,190.4 | 1,353 | 2,502.1 | 222 | 174.9 | 2,047 | 3,998.7 | 59 | 133.4 | 18,282 | 39,731.7 |
| Jan 31, 2020 | 22,555 | 21,134.4 | 2,249 | 2,737.4 | 178 | 204.0 | 3,987 | 4,120.6 | 77 | 138.4 | 43,271 | 40,210.0 |
| Jan 30, 2020 | 24,285 | 21,115.9 | 2,796 | 2,912.4 | 254 | 248.7 | 4,788 | 4,166.3 | 101 | 145.9 | 51,201 | 40,174.9 |
| Jan 29, 2020 | 26,021 | 21,036.1 | 2,744 | 3,130.0 | 240 | 254.0 | 4,934 | 4,218.9 | 214 | 134.6 | 50,384 | 40,118.4 |
| Jan 28, 2020 | 25,325 | 21,737.4 | 3,325 | 3,361.7 | 183 | 253.4 | 5,152 | 4,192.9 | 154 | 133.7 | 50,165 | 41,403.4 |
| Jan 27, 2020 | 22,665 | 20,609.6 | 2,933 | 4,331.1 | 203 | 250.0 | 4,389 | 4,211.0 | 124 | 133.1 | 43,208 | 41,317.3 |
| Jan 26, 2020 | 13,715 | 18,650.3 | 1,671 | 5,557.6 | 80 | 261.0 | 2,189 | 4,243.4 | 113 | 126.9 | 19,705 | 41,009.7 |
| Jan 25, 2020 | 13,767 | 16,683.6 | 1,797 | 6,853.7 | 86 | 282.6 | 2,552 | 4,314.4 | 151 | 111.6 | 20,188 | 41,024.7 |
| Jan 24, 2020 | 22,163 | 13,517.4 | 3,896 | 9,030.1 | 382 | 278.3 | 4,840 | 4,382.7 | 112 | 103.1 | 46,619 | 40,789.6 |
| Jan 23, 2020 | 24,155 | 10,066.7 | 4,021 | 11,427.6 | 567 | 253.1 | 5,108 | 4,624.9 | 153 | 91.0 | 50,955 | 40,569.6 |
| Jan 22, 2020 | 25,463 | 6,429.1 | 4,267 | 14,262.6 | 277 | 247.7 | 5,302 | 4,869.0 | 135 | 84.1 | 49,989 | 40,604.9 |
| Jan 21, 2020 | 30,234 | 2,110.0 | 4,947 | 17,241.9 | 179 | 262.3 | 4,970 | 5,174.9 | 148 | 73.1 | 59,160 | 40,074.6 |
| Jan 20, 2020 | 14,770 | 0.0 | 9,719 | 18,770.1 | 179 | 292.1 | 4,516 | 5,375.6 | 120 | 70.6 | 42,605 | 40,282.6 |
| Jan 19, 2020 | 0 | 0.0 | 10,256 | 19,153.1 | 157 | 285.3 | 2,416 | 5,474.9 | 69 | 74.3 | 17,552 | 40,611.7 |
| Jan 18, 2020 |  | 0.0 | 10,870 | 19,578.7 | 237 | 282.4 | 3,049 | 5,471.3 | 44 | 83.0 | 20,293 | 40,820.0 |
| Jan 17, 2020 |  | 0.0 | 19,131 | 20,410.9 | 352 | 304.3 | 5,318 | 5,585.4 | 53 | 82.6 | 44,973 | 41,397.3 |
| Jan 16, 2020 |  | 0.0 | 20,803 | 20,882.9 | 391 | 321.1 | 6,803 | 5,572.4 | 68 | 81.6 | 49,415 | 41,525.4 |
| Jan 15, 2020 |  | 0.0 | 24,112 | 20,800.4 | 239 | 363.4 | 7,011 | 5,442.0 | 87 | 74.1 | 50,236 | 41,696.7 |
| Jan 14, 2020 |  | 0.0 | 25,802 | 20,357.3 | 281 | 449.9 | 7,111 | 5,164.6 | 71 | 74.4 | 55,448 | 40,581.7 |
| Jan 13, 2020 |  | 0.0 | 20,417 | 20,388.3 | 388 | 507.4 | 5,921 | 4,966.9 | 102 | 65.9 | 44,061 | 39,891.9 |
| Jan 12, 2020 |  | 0.0 | 12,937 | 20,507.0 | 109 | 571.1 | 3,111 | 4,837.0 | 95 | 55.9 | 19,856 | 39,638.4 |
| Jan 11, 2020 |  | 0.0 | 13,849 | 20,365.7 | 217 | 622.4 | 3,024 | 4,765.7 | 105 | 49.9 | 21,751 | 39,311.0 |
| Jan 10, 2020 |  | 0.0 | 24,956 | 17,818.0 | 505 | 2,579.0 | 6,117 | 4,463.4 | 50 | 44.7 | 49,014 | 37,285.4 |
| Jan 9, 2020 |  | 0.0 | 24,107 | 14,374.1 | 509 | 5,483.3 | 6,712 | 4,172.6 | 61 | 47.6 | 50,312 | 34,995.1 |
| Jan 8, 2020 |  | 0.0 | 23,535 | 11,012.0 | 535 | 5,914.1 | 6,098 | 4,354.6 | 35 | 50.7 | 51,435 | 30,000.7 |
| Jan 7, 2020 |  | 0.0 | 22,700 | 7,769.1 | 886 | 5,787.6 | 5,169 | 5,222.3 | 73 | 45.7 | 47,643 | 26,628.1 |
| Jan 6, 2020 |  | 0.0 | 20,634 | 4,821.4 | 791 | 5,674.6 | 4,537 | 6,594.6 | 42 | 40.7 | 39,232 | 25,266.3 |
| Jan 5, 2020 |  | 0.0 | 13,768 | 2,854.6 | 555 | 5,595.3 | 2,202 | 7,527.3 | 25 | 38.7 | 18,082 | 25,093.3 |
| Jan 4, 2020 |  | 0.0 | 12,860 | 1,017.4 | 576 | 5,513.0 | 2,525 | 8,346.7 | 63 | 32.3 | 19,459 | 24,640.1 |
| Jan 3, 2020 |  | 0.0 | 7,122 | 0.0 | 14,201 | 3,484.3 | 4,001 | 9,262.7 | 14 | 32.1 | 34,835 | 23,140.1 |
| Jan 2, 2020 |  | 0.0 | 0 | 0.0 | 20,839 | 507.3 | 4,676 | 9,964.7 | 81 | 23.4 | 34,280 | 21,414.6 |
| Jan 1, 2020 |  | 0.0 |  | 0.0 | 3,551 | 0.0 | 7,372 | 10,148.9 | 57 | 17.3 | 16,474 | 21,315.7 |
| Dec 31, 2019 |  | 0.0 |  | 0.0 | 0 | 0.0 | 11,243 | 10,014.9 | 38 | 14.3 | 24,035 | 21,183.4 |
| Dec 30, 2019 |  | 0.0 |  | 0.0 |  | 0.0 | 14,143 | 9,772.9 | 7 | 14.3 | 29,699 | 21,819.7 |
| Dec 29, 2019 |  | 0.0 |  | 0.0 |  | 0.0 | 8,731 | 9,834.4 | 11 | 14.7 | 16,871 | 21,945.6 |
| Dec 28, 2019 |  | 0.0 |  | 0.0 |  | 0.0 | 8,261 | 9,892.7 | 18 | 17.7 | 16,287 | 22,282.4 |
| Dec 27, 2019 |  | 0.0 |  | 0.0 |  | 0.0 | 10,413 | 10,673.3 | 13 | 21.1 | 24,335 | 25,837.7 |
| Dec 26, 2019 |  | 0.0 |  | 0.0 |  | 0.0 | 9,590 | 11,686.1 | 20 | 23.3 | 22,201 | 29,675.7 |
| Dec 25, 2019 |  | 0.0 |  | 0.0 |  | 0.0 | 8,661 | 12,833.3 | 14 | 23.7 | 15,782 | 34,201.0 |
| Dec 24, 2019 |  | 0.0 |  | 0.0 |  | 0.0 | 10,305 | 13,712.6 | 17 | 21.9 | 23,109 | 37,771.9 |
| Dec 23, 2019 |  | 0.0 |  | 0.0 |  | 0.0 | 12,449 | 14,281.4 | 7 | 25.9 | 34,153 | 40,630.7 |
| Dec 22, 2019 |  | 0.0 |  | 0.0 |  | 0.0 | 9,162 | 14,187.7 | 14 | 35.4 | 17,752 | 40,860.3 |
| Dec 21, 2019 |  | 0.0 |  | 0.0 |  | 0.0 | 8,669 | 14,199.6 | 39 | 36.4 | 18,645 | 40,858.9 |
| Dec 20, 2019 |  | 0.0 |  | 0.0 |  | 0.0 | 15,877 | 14,226.3 | 37 | 36.7 | 49,222 | 40,525.0 |
| Dec 19, 2019 |  | 0.0 |  | 0.0 |  | 0.0 | 16,680 | 14,303.4 | 35 | 35.4 | 49,067 | 41,281.4 |
| Dec 18, 2019 |  | 0.0 |  | 0.0 |  | 0.0 | 16,691 | 14,456.4 | 17 | 35.9 | 47,459 | 41,951.1 |
| Dec 17, 2019 |  | 0.0 |  | 0.0 |  | 0.0 | 16,460 | 14,911.1 | 4 | 35.4 | 48,105 | 43,128.3 |
| Dec 16, 2019 |  | 0.0 |  | 0.0 |  | 0.0 | 16,431 | 15,196.7 | 35 | 31.3 | 54,165 | 42,803.3 |
| Dec 15, 2019 |  | 0.0 |  | 0.0 |  | 0.0 | 8,506 | 15,245.4 | 81 | 22.1 | 19,359 | 42,640.7 |
| Dec 14, 2019 |  | 0.0 |  | 0.0 |  | 0.0 | 8,752 | 15,439.4 | 46 | 17.4 | 18,635 | 43,083.4 |
| Dec 13, 2019 |  | 0.0 |  | 0.0 |  | 0.0 | 16,064 | 15,933.0 | 39 | 11.9 | 46,885 | 43,825.4 |
| Dec 12, 2019 |  | 0.0 |  | 0.0 |  | 0.0 | 17,220 | 16,463.6 | 26 | 8.1 | 54,362 | 43,621.6 |
| Dec 11, 2019 |  | 0.0 |  | 0.0 |  | 0.0 | 17,762 | 16,974.3 | 20 | 6.1 | 52,147 | 44,024.3 |
| Dec 10, 2019 |  | 0.0 |  | 0.0 |  | 0.0 | 19,643 | 17,088.1 | 1 | 6.6 | 56,345 | 43,916.7 |
| Dec 9, 2019 |  | 0.0 |  | 0.0 |  | 0.0 | 18,430 | 17,503.6 | 6 | 7.9 | 51,890 | 44,488.0 |
| Dec 8, 2019 |  | 0.0 |  | 0.0 |  | 0.0 | 8,847 | 18,091.0 | 17 | 142.0 | 18,221 | 45,216.3 |
| Dec 7, 2019 |  | 0.0 |  | 0.0 |  | 0.0 | 10,110 | 16,646.7 | 13 | 196.9 | 21,734 | 46,499.9 |
| Dec 6, 2019 |  | 0.0 |  | 0.0 |  | 0.0 | 19,519 | 13,858.3 | 0 | 196.9 | 52,079 | 46,089.1 |
| Dec 5, 2019 |  | 0.0 |  | 0.0 |  | 0.0 | 20,934 | 10,867.7 | 0 | 196.9 | 52,935 | 46,101.1 |
| Dec 4, 2019 |  | 0.0 |  | 0.0 |  | 0.0 | 21,337 | 7,819.6 | 6 | 196.0 | 54,966 | 47,876.6 |
| Dec 3, 2019 |  | 0.0 |  | 0.0 |  | 0.0 | 20,440 | 4,899.6 | 4 | 195.4 | 55,592 | 49,928.3 |
| Dec 2, 2019 |  | 0.0 |  | 0.0 |  | 0.0 | 21,338 | 1,851.3 | 15 | 193.3 | 55,889 | 53,400.9 |
| Dec 1, 2019 |  | 0.0 |  | 0.0 |  | 0.0 | 12,959 | 0.0 | 956 | 56.7 | 23,319 | 54,430.1 |
| Nov 30, 2019 |  | 0.0 |  | 0.0 |  | 0.0 | 0 | 0.0 | 397 | 0.0 | 30,719 | 54,780.4 |
| Nov 29, 2019 |  | 0.0 |  | 0.0 |  | 0.0 |  | 0.0 | 0 | 0.0 | 49,204 | 58,147.1 |
| Nov 28, 2019 |  | 0.0 |  | 0.0 |  | 0.0 |  | 0.0 |  | 0.0 | 53,019 | 61,091.6 |
| Nov 27, 2019 |  | 0.0 |  | 0.0 |  | 0.0 |  | 0.0 |  | 0.0 | 67,394 | 62,192.0 |
| Nov 26, 2019 |  | 0.0 |  | 0.0 |  | 0.0 |  | 0.0 |  | 0.0 | 69,954 | 62,355.0 |
| Nov 25, 2019 |  | 0.0 |  | 0.0 |  | 0.0 |  | 0.0 |  | 0.0 | 80,197 | 59,973.0 |
| Nov 24, 2019 |  | 0.0 |  | 0.0 |  | 0.0 |  | 0.0 |  | 0.0 | 30,524 | 59,892.1 |
| Nov 23, 2019 |  | 0.0 |  | 0.0 |  | 0.0 |  | 0.0 |  | 0.0 | 33,171 | 59,907.0 |
| Nov 22, 2019 |  | 0.0 |  | 0.0 |  | 0.0 |  | 0.0 |  | 0.0 | 72,771 | 58,619.0 |
| Nov 21, 2019 |  | 0.0 |  | 0.0 |  | 0.0 |  | 0.0 |  | 0.0 | 73,630 | 48,100.4 |
| Nov 20, 2019 |  |  |  |  |  |  |  |  |  |  | 75,097 |  |
| Nov 19, 2019 |  |  |  |  |  |  |  |  |  |  | 71,095 |  |
| Nov 18, 2019 |  |  |  |  |  |  |  |  |  |  | 63,523 |  |
| Nov 17, 2019 |  |  |  |  |  |  |  |  |  |  | 29,958 |  |
| Nov 16, 2019 |  |  |  |  |  |  |  |  |  |  | 33,275 |  |
| Nov 15, 2019 |  |  |  |  |  |  |  |  |  |  | 63,755 |  |
| Nov 14, 2019 | 0 |  | 0 |  | 0 |  | 0 |  | 0 |  | 0 |  | 
 https://crates.io/crates/syn
